name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          git add .
          git commit -m "Deploy site to GitHub Pages"
          git push origin gh-pages
